#!/bin/sh

# =========================
# CURSOR
# =========================
 xrdb -merge ~/.Xresources &
 xsetroot -cursor_name left_ptr &
 lxappearance --init &

# Define monitors (replace eDP-1 and HDMI-1 with your outputs from xrandr)

# MONITOR_MAIN="eDP-1"
# MONITOR_EXT="HDMI-1"

# Distribution of workspaces across monitors

# bspc monitor $MONITOR_MAIN -d 1 2 3 4 5
# if xrandr | grep "$MONITOR_EXT connected"; then
#     bspc monitor $MONITOR_EXT -d 6 7 8 9 10
#     # Запуск Polybar на обоих мониторах
#     polybar main_bar &
#     polybar ext_bar &
# else
#     bspc monitor $MONITOR_MAIN -d 1 2 3 4 5 6 7 8 9 10
#     polybar main_bar &
# fi

# =========================
# BSPWM CORE
# =========================
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width        1
bspc config window_gap          40
bspc config split_ratio 	0.52

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false

bspc config automatic_scheme spiral
# bspc config automatic_scheme longest_side

# =========================
# COLORS & MOUSE
# =========================
bspc config focused_border_color "#ffffff"
bspc config normal_border_color  "#eff1e4"
bspc config active_border_color  "#ffffff"

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# =========================
# RULES xprop WM_CLASS
# =========================
 bspc rule -r all

 bspc rule -a Rofi state=floating rectangle=0x0+0+0 center=on

 # bspc rule -a firefox desktop=1
 # bspc rule -a Thunar desktop=2
 # bspc rule -a code desktop=4
 # bspc rule -a mpv desktop=5
 # bspc rule -a Org.gnome.Rhythmbox3 desktop=5
 # bspc rule -a io.github.celluloid_player.Celluloid desktop=5
 # bspc rule -a imv desktop=6
 # bspc rule -a Mousepad desktop=3 follow=on && mousepad &

# =========================
# SERVICES & INPUT
# =========================
pgrep -x sxhkd >/dev/null || sxhkd &
setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle" &

# =========================
# POLYBAR & NOTIFICATIONS
# =========================
~/.config/polybar/launch.sh &
dunst -config ~/.config/dunstrc &

# =========================
# GRAPHICS
# =========================
feh --bg-fill ~/Pictures/nohara.jpg &
picom --config ~/.config/picom/picom.conf 

# exec bspwm
