########################################
# polybar @yojeero - Paper Theme
# https://coolors.co/fdfdfd/variations
#########################################

# transparents - insert before color 
# 10% — 1A
# 20% — 33
# 30% — 4D
# 40% — 66
# 50% — 80
# 60% — 99
# 70% — B3
# 80% — CC
# 90% — E6

[colors]
background = #80ffffff
foreground = #696969

space = #5E5C64
accent = #9A9996

red    = #FB607F
purple  = #BCBCED
blue   = #7dc4e4
orange = #ffc300
green = #71D044

[bar/top]
width = 70%
height = 40

radius = 0.0
radius-bottom = 12.0
radius-bottom-left = 12.0
radius-bottom-right = 12.0
radius-top-left = 0.0
radius-top-right = 0.0

border-size = 1
border-color = #ffffff

background = ${colors.background}
foreground = ${colors.foreground}

offset-x = 15%
offset-y = 0

padding-left = 4
padding-right = 4

fixed-center = true
monitor-strict = false

modules-left = rofi bspwm
modules-center = date
modules-right = xkeyboard space pulseaudio space wlan ethernet space powermenu

# modules-right = temperature space memory space cpu space

font-0 = "Terminess Nerd Font:size=10;2"
font-1 = "Symbols Nerd Font Mono:size=9;2"

enable-ipc = true

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; modules
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/rofi]
type = custom/text

content = " "
#content = "    󰶞"
content-padding = 1
content-font = 2
content-foreground = ${colors.red}

click-left = rofi -show drun
click-right = rofi -no-grab -show drun

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
occupied-scroll = false

ws-icon-0 = 1;󰈹
ws-icon-1 = 2;󰝰
ws-icon-2 = 3; 
ws-icon-3 = 4;
ws-icon-4 = 5;󰎆
ws-icon-5 = 6;

# ws-icon-default = 󰷏  

format = <label-state>
format-font = 2

label-focused = %icon%
# label-focused = %name%
label-focused-foreground = ${colors.blue}
label-focused-padding = 2
label-focused-underline = ${colors.blue}

label-occupied = %icon%
# label-occupied = %name%
label-occupied-foreground= ${colors.orange}
label-occupied-padding = 2

label-urgent = %icon%
# label-urgent = %name%
label-urgent-foreground = ${colors.red}
label-urgent-padding = 2

label-empty = %icon%
# label-empty = %name%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/date]
type = internal/date
interval = 1.0

date = "%H:%M  -  %a, %d %b"

time = "%H:%M"
label = %date% %time%

format-prefix = "  "
format-prefix-foreground = ${colors.blue}
format-font = 2

format = <label>
label-foreground = ${colors.foreground}
label-font = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 75

format = <ramp><label>
format-warn = <ramp> <label-warn>
format-font = 2

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.red}
label-font = 1

ramp-0 = " "
ramp-foreground = ${colors.blue}
label-foreground = ${colors.foreground}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/memory]
type = internal/memory

format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.blue}
format-font = 2

label = %gb_used%
label-foreground = ${colors.foreground}
label-font = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/cpu]
type = internal/cpu

format-prefix = "  "
format-prefix-foreground = ${colors.blue}
format = <label>
format-font = 2

label = %percentage%%
label-foreground = ${colors.foreground}
label-font = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/xkeyboard]
type = internal/xkeyboard

format = <label-layout> <label-indicator>
format-prefix = "  "
format-prefix-foreground = ${colors.blue}
format-font = 2

label-layout-foreground = ${colors.foreground}
label-font = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.green}
format-volume = <label-volume>
format-volume-font = 2

label-volume = %percentage%%
label-volume-foreground = ${colors.foreground}
label-font = 1

label-muted = "  "
label-muted-foreground = ${colors.red}
label-muted-font = 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/wlan]
type = internal/network
interface-type = wireless

format-connected = <label-connected>
format-connected-foreground = ${colors.orange}

format-disconnected = <label-disconnected>
format-disconnected-padding = 1
format-disconnected-foreground = ${colors.red}
format-connected-font = 2

label-connected = "  %essid%"
label-connected-foreground = ${colors.foreground}
label-disconnected = "  offline"
label-disconnected-foreground = ${colors.foreground}
label-disconnected-font = 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/ethernet]
type = internal/network
interface = enp8s0
interface-type = wired

format-connected = <label-connected>
format-connected-prefix-foreground = ${colors.orange}

format-disconnected = <label-disconnected>
format-disconnected-prefix-foreground = ${colors.red}
format-connected-font = 2

label-connected = " 󰌘 "
label-connected-foreground = ${colors.orange}

label-disconnected = " 󰌙 "
label-disconnected-foreground = ${colors.red}
label-disconnected-font = 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/powermenu]
type = custom/text

content = 
content-font = 2

content-foreground = ${colors.purple}
# content-padding = 1

click-left = rofi -modi "power:$HOME/.config/rofi/power.sh" -show power -theme $HOME/.config/rofi/powermenu.rasi

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/space]
type = custom/text

content = " / "
content-padding = 1
content-foreground = ${colors.space}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[settings]
screenchange-reload = true
pseudo-transparency = true
